spring:
  profiles:
    active: chaos-monkey


management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - chaosmonkey
chaos:
  monkey:
    watcher:
      repository: true
      rest-controller: true
      controller: true
      service: true